# -*- coding: utf-8 -*-
"""Chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U2Ac1mIVj_kXOvLqMpDlvoQAawn4uoRG
"""

pip install nltk

import random

import nltk

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')

data = {
  "intents": [

    {
      "tag": "greeting",
      "patterns": [
        "hi", "hello", "hey", "hii", "hey there",
        "good morning", "good afternoon", "good evening",
        "howdy", "what's up", "greetings"
      ],
      "responses": [
        "Hello! Welcome to our college helpdesk. How can I assist you today?",
        "Hi there! I'm here to help you with any queries about our college.",
        "Hey! Feel free to ask me anything about admissions, courses, or campus life."
      ]
    },

    {
      "tag": "goodbye",
      "patterns": [
        "bye", "goodbye", "see you", "take care",
        "exit", "quit", "see you later", "catch you later",
        "i'm done", "that's all", "thanks bye"
      ],
      "responses": [
        "Goodbye! Best of luck with your admission journey!",
        "See you later! Don't hesitate to reach out if you have more questions.",
        "Take care! Wishing you all the best."
      ]
    },

    {
      "tag": "thanks",
      "patterns": [
        "thanks", "thank you", "thanks a lot", "thank you so much",
        "that was helpful", "very helpful", "appreciate it",
        "great help", "cheers"
      ],
      "responses": [
        "You're welcome! Is there anything else I can help you with?",
        "Glad I could help! Feel free to ask if you have more questions.",
        "Anytime! Don't hesitate to reach out."
      ]
    },

    {
      "tag": "courses",
      "patterns": [
        "courses", "programs", "what courses do you offer",
        "available courses", "course list", "course information",
        "tell me about your programs", "what can i study here",
        "undergraduate courses", "postgraduate courses",
        "btech", "mtech", "mba", "diploma", "degree programs",
        "engineering branches", "which stream", "which specialization"
      ],
      "responses": [
        "We offer a range of programs including BTech (CSE, IT, Mechanical, Civil, Electronics), MTech, MBA, and Diploma courses. Which program would you like to know more about?",
        "Our college provides undergraduate and postgraduate programs. BTech is available in branches like Computer Science, IT, Mechanical, and more. Would you like details on a specific course?"
      ]
    },

    {
      "tag": "fees",
      "patterns": [
        "fees", "cost", "how much", "fee structure",
        "tuition fees", "annual fees", "semester fees",
        "how much does btech cost", "btech fees",
        "mba fees", "mtech fees", "is it affordable",
        "scholarship", "fee waiver", "financial aid"
      ],
      "responses": [
        "The fee structure varies by program. BTech costs approximately ₹1 lakh per year, while MBA is around ₹1.5 lakh per year. Scholarships are also available for eligible students.",
        "BTech fees are roughly ₹1 lakh per year. We also offer merit-based and need-based scholarships. Would you like information about a specific course's fee?"
      ]
    },

    {
      "tag": "admission",
      "patterns": [
        "admission", "how to apply", "application process",
        "how do i get admission", "enrollment", "registration",
        "admission procedure", "when does admission start",
        "admission deadline", "last date to apply",
        "documents required", "eligibility", "cutoff",
        "entrance exam", "merit based", "what marks do i need"
      ],
      "responses": [
        "Admissions are open for the upcoming academic year. You can apply online through our official website. Eligibility for BTech requires 10+2 with Physics, Chemistry, and Maths. Would you like help with the application steps?",
        "The admission process is conducted online. Submit your application form, upload required documents, and pay the registration fee. Shortlisting is based on entrance scores or merit. Shall I walk you through the steps?"
      ]
    },

    {
      "tag": "location",
      "patterns": [
        "where is the college", "location", "address",
        "how to reach", "directions", "campus location",
        "where are you located", "which city", "which area",
        "near which station", "how far", "transport",
        "nearest bus stop", "nearest railway station"
      ],
      "responses": [
        "Our campus is located in Mumbai. It is well connected by public transport — the nearest railway station is about 2 km away. Would you like directions?",
        "The college is situated in Mumbai and is easily accessible by bus and train. Feel free to ask for specific directions."
      ]
    },

    {
      "tag": "hostel",
      "patterns": [
        "hostel", "accommodation", "where will i stay",
        "is hostel available", "hostel facility", "hostel fees",
        "boys hostel", "girls hostel", "pg accommodation",
        "on campus stay", "room facility", "dormitory",
        "hostel food", "hostel rules", "hostel warden"
      ],
      "responses": [
        "Yes, we have separate hostel facilities for boys and girls on campus. The hostel includes furnished rooms, Wi-Fi, and a mess facility. Hostel fees are charged separately.",
        "On-campus accommodation is available for students. The hostel provides a safe and comfortable environment with all basic amenities. Would you like to know about hostel fees or facilities?"
      ]
    },

    {
      "tag": "placements",
      "patterns": [
        "placements", "placement record", "campus recruitment",
        "job after college", "which companies come", "package",
        "highest package", "average salary", "placement cell",
        "internship", "training and placement", "job opportunities",
        "placement percentage", "top recruiters"
      ],
      "responses": [
        "Our placement cell has an excellent record with over 90% placement rate. Top recruiters include companies like TCS, Infosys, Wipro, and various startups. The average package is around ₹4–6 LPA.",
        "We have a dedicated Training and Placement cell. Students receive pre-placement training, mock interviews, and career guidance. Many students have also secured internships at top MNCs."
      ]
    },

    {
      "tag": "faculty",
      "patterns": [
        "faculty", "teachers", "professors", "staff",
        "who teaches here", "teaching staff",
        "are teachers qualified", "phd professors",
        "faculty details", "department faculty",
        "faculty experience", "visiting faculty"
      ],
      "responses": [
        "Our faculty includes experienced professors, many of whom hold PhDs from reputed universities. We also invite industry experts as visiting faculty for practical exposure.",
        "The teaching staff is highly qualified and experienced. Faculty members are actively involved in research and industry collaborations, ensuring students receive a well-rounded education."
      ]
    },

    {
      "tag": "library",
      "patterns": [
        "library", "books", "reading room", "study material",
        "e-library", "digital library", "journals",
        "library timings", "library membership",
        "research papers", "reference books"
      ],
      "responses": [
        "Our library is well-stocked with over 20,000 books, academic journals, and digital resources. Students also have access to an e-library with research papers and reference materials.",
        "The college library offers a wide range of textbooks, reference books, and online databases. There is also a dedicated reading room for focused study."
      ]
    },

    {
      "tag": "sports",
      "patterns": [
        "sports", "games", "playground", "sports facilities",
        "cricket", "football", "basketball", "gym",
        "extracurricular", "outdoor activities", "indoor games",
        "sports events", "annual sports day", "athletic"
      ],
      "responses": [
        "We have excellent sports facilities including grounds for cricket, football, and basketball, along with a fully equipped gymnasium. Inter-college sports events are held regularly.",
        "Sports and physical fitness are encouraged here. Students can participate in indoor and outdoor games, and we hold an annual sports day with competitions across multiple disciplines."
      ]
    },

    {
      "tag": "canteen",
      "patterns": [
        "canteen", "food", "cafeteria", "mess",
        "what food is available", "is food good",
        "canteen timings", "veg or nonveg",
        "is food hygienic", "lunch", "snacks", "tiffin"
      ],
      "responses": [
        "The campus canteen serves fresh, hygienic vegetarian and non-vegetarian meals at affordable prices. It is open from 8 AM to 8 PM on weekdays.",
        "We have a well-maintained cafeteria offering a variety of meals and snacks. Special menu items are available during festivals and events."
      ]
    },

    {
      "tag": "exams",
      "patterns": [
        "exams", "test schedule", "exam timetable",
        "how are exams conducted", "evaluation pattern",
        "internal marks", "external marks", "university exam",
        "mid semester", "end semester", "passing criteria",
        "revaluation", "backlog", "exam fees"
      ],
      "responses": [
        "Exams are conducted semester-wise, with both internal assessments and end-semester university exams. The internal to external marks ratio is typically 40:60.",
        "The evaluation system includes continuous internal assessment through assignments and mid-terms, followed by a university-conducted end-semester exam. Results are usually declared within 4–6 weeks."
      ]
    },

    {
      "tag": "contact",
      "patterns": [
        "contact", "phone number", "email address",
        "how do i reach you", "contact details",
        "helpline", "admission helpdesk", "office number",
        "support", "get in touch", "official website"
      ],
      "responses": [
        "You can reach us through the official website's contact form, or call the admissions helpdesk during working hours (Mon–Sat, 9 AM to 5 PM).",
        "For inquiries, visit our official website or drop an email to the admissions office. Our team typically responds within 1–2 working days."
      ]
    },

    {
      "tag": "clubs",
      "patterns": [
        "clubs", "student clubs", "extracurricular",
        "student activities", "cultural events", "technical fest",
        "coding club", "dance club", "music club",
        "student council", "nss", "ncc", "committees"
      ],
      "responses": [
        "We have a vibrant student community with clubs for coding, robotics, music, dance, drama, and more. Cultural and technical fests are held every year.",
        "Students can join various clubs and committees based on their interests. NSS, NCC, and student council opportunities are also available."
      ]
    },

    {
      "tag": "infrastructure",
      "patterns": [
        "infrastructure", "campus", "classrooms",
        "labs", "computer lab", "wifi", "internet",
        "facilities", "campus tour", "smart class",
        "auditorium", "seminar hall", "parking"
      ],
      "responses": [
        "Our campus is equipped with modern classrooms, fully functional computer and science labs, a large auditorium, seminar halls, and high-speed Wi-Fi throughout.",
        "The infrastructure includes state-of-the-art labs, smart classrooms, a sports complex, and ample parking. We are continuously upgrading our facilities to meet industry standards."
      ]
    }

  ]
}

def preprocess(text):
    stopwords = ["about", "inquire", "tell", "me", "please", "the", "is", "a"]
    words = text.lower().split()
    return [word for word in words if word not in stopwords]

def get_response(user_input):
    user_words = preprocess(user_input)

    for intent in data["intents"]:
        for pattern in intent["patterns"]:
            pattern_words = preprocess(pattern)

            if any(word in pattern_words for word in user_words):
                return intent["responses"][0]

    return "Sorry, I didn't understand."

from nltk.corpus import wordnet

def get_synonyms(word):
    synonyms = set()
    for syn in wordnet.synsets(word):
        for lemma in syn.lemmas():
            synonyms.add(lemma.name())
    return synonyms

def match(user_words, pattern_words):
    for word in user_words:
        synonyms = get_synonyms(word)
        if word in pattern_words or any(s in pattern_words for s in synonyms):
            return True
    return False

context = None

def get_response(user_input):
    global context
    user_words = preprocess(user_input)

    best_intent = None
    best_score = 0

    for intent in data["intents"]:
        for pattern in intent["patterns"]:
            pattern_words = preprocess(pattern)

            score = 0
            for word in user_words:
                if word in pattern_words:
                    score += 1
                else:
                    synonyms = get_synonyms(word)
                    if any(s in pattern_words for s in synonyms):
                        score += 1

            if score > best_score:
                best_score = score
                best_intent = intent

    if best_score > 0 and best_intent:
        context = best_intent["tag"]
        return random.choice(best_intent["responses"])

    return "Sorry, I didn't understand."

print("Chatbot is running (type 'quit' to exit)")

while True:
    user_input = input("You: ")

    if user_input.lower() == "quit":
        break

    response = get_response(user_input)
    print("Bot:", response)